# a gps file for tesing

/gps/particle gamma
/gps/ene/type Pow
/gps/ene/min 10 keV
/gps/ene/max 500 keV
/gps/ene/alpha -1.0

/gps/pos/type Plane
/gps/pos/shape Rectangle
 /gps/pos/rot1 0.5 -0.866 0
/gps/pos/rot2 -0.94 0 0.33
/gps/pos/centre -43.4 25.04 141.4 cm
#/gps/pos/centre 0.0.0 0.0 150.0 cm
/gps/pos/halfx 25.0 cm
/gps/pos/halfy 25.0 cm
/gps/direction 0.286 -0.165 -0.94

#/gps/polarization 1 0 0

